# from http://www.agls.gov.au/documents/agls-audience/
agls_audience = {
    'Aboriginal and Torres Strait Islanders': 'People who identify themselves as part of the Indigenous Australian community.',
    'all': 'Default value; general public; the whole population.',
    'Australian Antarctic Territory': 'Persons living or working in the Australian Antarctic Territory.',
    'Australian Capital Territory': 'Persons living or working in the Australian Capital Territory.',
    'Australians overseas': 'Citizens of Australia living, working or travelling overseas.',
    'business': 'Persons or corporations engaged in commerce, trade or industry.',
    'carers': 'Persons or organisations engaged in the care of others (eg patients, children, elderly, disabled). Use ‘parents’ for resources aimed at mothers, fathers or legal guardians.',
    'children': 'Persons under the age of 16 years. Use ‘youth’ for resources aimed at persons aged 16–25 years.',
    'community groups': 'Groups who provide services to, or represent the views of, specific community sectors.',
    'employees': 'Persons working for another person or business for wages. Use ‘jobseekers’ for resources designed to assist people seeking employment.',
    'employers': 'Persons or businesses who employ others for wages.',
    'funding applicants': 'Persons, organisations or businesses seeking funding from government grant or other financial assistance programs.',
    'gay and lesbian': 'Persons who identify themselves as part of the homosexual community.',
    'government': 'Agencies and organisations associated with public administration at local, state or federal level.',
    'Indian Ocean Territories': 'Persons living or working in the Indian Ocean Territories.',
    'jobseekers': 'Persons seeking employment, whether currently employed or unemployed. Use ‘employees’ for resources of relevance to people already in employment.',
    'low income earners': 'As determined by the Australian Taxation Office, persons whose annual income is less than $28,980 (current at 2007-07-01).',
    'media': 'Organisations that by means such as radio, television, newspapers, magazines, Internet etc reach large numbers of people.',
    'men': 'Adult male persons.',
    'migrants': 'Persons moving permanently from one country to another, either from Australia to overseas, or from other countries to Australia. Includes resources for people from non-English-speaking backgrounds or who have English as a second language.',
    'New South Wales': 'Persons living or working in New South Wales.',
    'non-Australians': 'Persons not citizens of or resident in Australia. Use ‘Australians overseas’ for Australian citizens not resident in Australia.',
    'non-government organisations': 'Organisations not established by government, especially those involved in not-for-profit charitable, development, environmental or relief programs. Use \'business\' for organisations engaged in for-profit activities.',
    'Norfolk Island': 'Persons living or working in Norfolk Island.',
    'Northern Territory': 'Persons living or working in the Northern Territory.',
    'parents': 'Persons fulfilling a mother, father or guardian role in the care of children, whether by birth, adoption or other legal arrangement.',
    'people with disabilities': 'Persons with a physical or mental incapacity, either permanent or temporary.',
    'primary industry': 'Persons or organisations involved in the growing, producing or extracting of natural resources (eg, farming, forestry, mining). Use ‘rural’ for resources aimed at people and communities outside urban areas.',
    'Queensland': 'Persons living or working in Queensland.',
    'rural': 'Persons living or working in regional, country or isolated areas of Australia. Use ‘primary industry’ for resources on commercial activities that may occur in rural areas.',
    'seniors': 'Persons over the age of 65 years.',
    'South Australia': 'Persons living or working in South Australia.',
    'students': 'Persons engaged in a course of study or instruction whether at pre-primary, primary, secondary, vocational or tertiary level.',
    'Tasmania': 'Persons living or working in Tasmania.',
    'teachers': 'Members of the teaching profession, persons instructing students at pre-primary, primary, secondary, vocational or tertiary level.',
    'tourists': 'Persons visiting an area for pleasure, either from other countries or other parts of Australia. Use ‘migrants’ for persons relocating permanently to Australia.',
    'veterans': 'As defined in the Veterans’ Entitlements Act 1986 (Cth), persons taken to have rendered eligible war service.',
    'Victoria': 'Persons living or working in Victoria.',
    'Western Australia': 'Persons living or working in Western Australia.',
    'women': 'Adult female persons.',
    'youth': 'Persons aged 16–25 years. Use ‘children’ for resources aimed at persons under the age of 16 years.'
}

# http://www.agls.gov.au/documents/AglsJuri/
agls_jurisdiction = {
    'Australia': 'Commonwealth of Australia Constitution Act 1900 (UK)',
    'Australian Antarctic Territory': 'The Australian Antarctic Territory plus the subantarctic territories of Heard and McDonald Islands',
    'Australian Capital Territory': 'Seat of Government Surrender Act 1909 (NSW), Seat of Government Surrender Act 1915 (NSW)',
    'Indian Ocean Territories': 'Cocos (Keeling) Islands and Christmas Island',
    'New South Wales': 'Constitution Act 1902 (NSW)',
    'Norfolk Island': 'Norfolk Island Act 1979 (Cth)',
    'Northern Territory': 'Northern Territory Acceptance Act 1910 (Cth)',
    'Queensland': 'Letters Patent erecting the Colony of Queensland 1859 (UK), Letters Patent altering the western boundary of Queensland 1862 (UK), Queensland Coast Islands Act 1879 (Qld)',
    'South Australia': 'South Australian Act (Foundation Act) 1834 (UK), Letters Patent establishing the Province of South Australia 19 February 1836 (UK)',
    'Tasmania': 'Order-In-Council Separating Van Diemen’s Land From New South Wales 1825 (UK)',
    'Victoria': 'General Instructions to the Superintendent of Port Phillip, 1839',
    'Western Australia': 'WA 	Letters Patent re Constitution 25 August 1890 (UK)',
    'Other': 'Any other Australian jurisdiction not named here'
}

# http://www.agls.gov.au/documents/agls-document/
agls_document = {
    'act': 'An act of Commonwealth, state or territory legislatures.',
    'agenda': 'A list of issues or activities used as a schedule or program for an event, conference, forum or meeting.',
    'agreement': 'A summary or record of an arrangement between two or more parties.',
    'blog': 'Ongoing online commentary by an individual or organisation.',
    'checklist': 'Any listing of items or entries provided for reference purposes, including an inventory, register, directory or index. Use ‘dataset’ for bibliographic data or catalogues.',
    'contract': 'An agreement between two or more parties for the delivery of a product, provision of a service, or management of a resource.',
    'dataset': 'Structured information encoded in lists, tables, databases etc, (eg, spreadsheets, databases, GIS data). Data may be numeric, spatial, spectral, statistical or structured text (including bibliographic data and database reports).',
    'diary': 'Information arranged in calendar order documenting appointments and engagements. Use ‘journal’ for information arranged in calendar order documenting events, business or proceedings.',
    'digital certificate': 'Any form of electronic code that describes or provides permission to access a resource.',
    'digital signature': 'Any form of electronic code used to simulate the security properties of a handwritten signature or to establish authenticity.',
    'electronic message': 'Any electronically mediated communication. This includes but is not limited to electronic mail, text messages, instant messages, electronic voice messages, electronic video messages and computer conferencing.',
    'fact sheet': 'A summary of information about a product, service, organisation, event or topic.',
    'form': 'A structured solicitation of input from a user (eg, comments, a survey or an order). For forms used to provide a service (eg, enquiries, registrations, or orders and purchases) use category value \'service\' and select an appropriate value from the list of service types instead.',
    'government gazette': 'Regular formal publication produced by government that may include vacancies, appointments, bulletins, notices and legislative directives.',
    'guidelines': 'The primary purpose of the resource is to present factual information, advice or guidance about an organisation, event or service. Most general advisory pages on government websites will be of this document type. Use \'instructional\' for resources that provide directions rather than information.',
    'homepage': 'The introductory page or major entry point for a site on the Internet. In most cases an organisation will have only one resource of this document type, except where there is likely to be a public perception that a distinct business unit stands alone as an organisational entity.',
    'index': 'Any listing of items or entries provided for reference or navigation purposes, including an inventory, register or directory.',
    'instruction': 'Resources in which the primary purpose is to provide instructions or directions (eg, how to write a report; how to register for a service). Includes manuals, handbooks, tutorials and quizzes. Use \'guidelines\' for resources which have primarily informational content.',
    'journal': 'A record or register of events, business or proceedings.',
    'legislation': 'A legal mandate containing written laws apporved by Commonwealth, state or territory parliaments.',
    'letter': 'A written or printed communication addressed to a person or a number of persons, including scanned versions of written or printed communications, but excludes scanned versions of written or printed messages.',
    'log': 'A chronological listing of actions, observations, data or transactions.',
    'mandate': 'Any other legal instrument not listed here.',
    'release': 'Resources specifically designed to provide a brief public statement on an issue or event, via the mass media.',
    'meeting minutes': 'A summary or record of proceedings of a meeting.',
    'memorandum': 'A note describing something to be remembered or acted upon in the future.',
    'metadata': 'Data describing the context, content, structure and organisation of records and other information.',
    'minute': 'A form of correspondence acting as an official note or memorandum, usually recording an action or decision, or seeking approval for a course of action.',
    'image': 'A form of visual representation other than text, involving moving pictures, animation, video or film, with or without audio. For some resources it may be appropriate to use a combination of document types. (For example: video recording of an exhibition opening specify document types as \'promotion; moving image\'.)',
    'note for file': 'A summary or record of a less formal meeting or ad hoc discussion (including by telephone).',
    'other': 'Any document form not listed here.',
    'policy statement': 'A major formal publication detailing a course or line of action adopted and pursued by the organisation. Includes public accountability documents such as corporate directions and other strategic plans. Use \'report\' for resources that convey the results of an inquiry, account for activities or document speeches and presentations.',
    'procedure': 'A sequence of actions or instructions to be followed.',
    'presentation': 'Any form of visual and/or verbal communication used to show or explain a topic to an audience.',
    'promotion': 'Descriptive or marketing information about an organisation or material that promotes its products, services, activities or collections (eg, ‘What’s New’ pages, brochures). Includes announcements.',
    'regulation': 'A legal mandate that exists in a piece of subsidiary legislation, a regulation issued pursuant to an act.',
    'report': 'A resource providing an account of organisational activity or a speech or presentation. Includes statements of the organisation\'s opinion, a decision or the results of an inquiry. Use \'dataset\' for database reports.',
    'software': 'Computer programs in source or compiled form which may be available for installation on another machine. For software that exists only to create an interactive environment use category value \'service\' and choose the service type ‘communications forum’ instead.',
    'sound': 'The content is a primarily audio representation, which may be ambient, effects, music, narration or speech. For some audio resources it may be appropriate to use a combination of document types. For example: sound recording of a presentation specify document types as \'presentation; sound\'.',
    'standard': 'A set of requirements and/or specifications that either requires compliance by a particular group or application, or recommends best practice in a particular field.',
    'still image': 'The content is primarily a still visual representation other than text. Includes electronic and physical representations such as images, photographs, diagrams, maps and graphics. For digital representations of physical resources, use a more specific document type where possible. (For example: a scanned media release use \'media release; still image\').',
    'wiki': 'A collaborative website where content can be contributed or modified by users.'
}

# http://www.agls.gov.au/documents/agls-service/
agls_service = {
    'applications': 'The resource allows clients to make formal written requests of a general nature, which cannot be more specifically described by another term from the agls-service list. For some types of applications (eg, ‘grants’) a more specific service type may be listed.',
    'benefits and entitlements': 'The resource allows clients to apply for payments, allowances or concessions to which he/she has a right, usually as a result of personal circumstance (eg, unemployment, age, family benefits). See also ‘claims’ and ‘grants’. For other aspects of benefits and entitlements, use another service type from the list where available (eg, ‘complaints and appeals’, ‘enquiries’, ‘financial’).	',
    'bills, rates and levies': 'The resource allows clients to pay accounts, taxes or other charges. See also ‘orders and purchases’ and ‘infringements and fines’. For other aspects of bills, rates and levies, use another service type from the list where available (eg, ‘complaints and appeals’, ‘enquiries’, ‘refunds’).	',
    'bonds': 'The resource allows clients to pay sums of money, to be held in trust and paid in default of an agreement, contract or obligation. For other aspects of bonds, use another service type from the list where available (eg, ‘complaints and appeals’, ‘enquiries’, ‘refunds’).',
    'bookings and reservations': 'The resource allows clients to make (or cancel) engagements or secure places or objects in advance, for use at a later date. See also ‘enrolments’.',
    'business advisory': 'The resource allows clients to make formal requests for professional advice on business matters, such as enquiries on the setting up of a small business.',
    'certificates': 'The resource allows clients to request formal written statements of fact, endorsement or accreditation (eg, educational qualification, statement of attainment, birth certificate, certificate of registration). See also ‘licences and permits’ and ‘registrations’.	',
    'claims': 'The resource allows clients to make assertions or demands for the recognition of a right or due, usually in response to an event or activity (eg, title, insurance, taxation, compensation claims). See also ‘benefits and entitlements’, ‘complaints and appeals’ and ‘refunds’.',
    'communications forum': 'The resource is a setting designed exclusively for interactive involvement with one or more users (eg, chat services, listservs, virtual reality, multimedia learning objects).',
    'complaints and appeals': 'The resource allows clients to submit formal expressions of discontent, grievance or alleged offences. Includes requests for review of a decision or settlement. See also ‘claims’ and ‘lodgements’.',
    'data exchange': 'The resource allows clients to undertake electronic reporting, transfer or sharing of information.',
    'enquiries': 'The resource allows clients to submit questions and requests for advice and information. For some types of enquiries (eg, ‘business advisory’) a more specific service type may be listed.',
    'enrolments': 'The resource allows clients to register in a scheme or program for a conference or course of study etc.',
    'financial': 'The resource allows clients to undertake transactions relating to money or commercial matters. For some types of financial services (eg, ‘bills, rates and levies’) a more specific service type may be listed.',
    'grants': 'The resource allows clients to apply for sums of money or other resources bestowed upon approved individuals or institutions. Includes scholarships, endowments, awards and similar types of funding. For other aspects of grants, use another service type from the list where available (eg, ‘complaints and appeals’, ‘enquiries’).	',
    'infringements and fines': 'The resource allows clients to pay charges and other penalties imposed for breaches or violations of obligations, laws and other codes. For other aspects of infringements and fines, use another service type from the list where available (eg, ‘complaints and appeals’, ‘enquiries’, ‘refunds’).	',
    'legal advisory': 'The resource allows clients to make formal requests for professional advice or legal opinions.	',
    'licences and permits': 'The resource allows clients to apply for written orders or formal consent to do, or exemption from, an activity (eg, driving a car, owning a dog, tax exemption). Includes authorisations and approvals. For other aspects of licences and permits, use another service type from the list where available (eg, ‘complaints and appeals’, ‘enquiries’, ‘renewals’). See also ‘certificates’ and ‘registrations’.	',
    'lodgements': 'The resource allows clients to make formal statements or submissions to a court, tribunal, commission, inquiry or similar body. See also ‘complaints and appeals’.',
    'orders and purchases': 'The resource allows clients to make requests and/or payments for the delivery of goods or services. See also ‘subscriptions’.',
    'refunds': 'The resource allows clients to request reimbursements or compensation for non-supply of goods or services, or for supply of faulty goods or services. See also ‘claims’ and ‘complaints and appeals’.',
    'registrations': 'The resource allows clients to have recorded, acts, occurrences or items (eg, motor vehicles, letters posted, marriages, businesses). For registrations of participants in a scheme, program, conference or course, use ‘enrolments’. For registrations by a board (or similar) authorising an activity, use ‘licences and permits’. For formal statements that prove registration, use ‘certificates’.',
    'renewals': 'The resource allows clients to request that provision of an item or benefit be recommenced, or made effective for an additional period.',
    'subscription': 'The resource allows clients to request the provision of a service for a designated period of time, often in return for payment of a fee (eg, membership of a group, shares, periodicals). See also ‘renewals’.',
    'technical': 'The resource allows clients to access specialised services of a scientific, industrial or mechanical nature, for which a more specific service type is not listed.',
    'tenders': 'The resource allows providers to submit formal offers to supply goods or services with a stated price and terms. Includes bids, offers, proposals and estimates.',
    'testing': 'Services that examine, investigate, analyse or check the performance or capabilities of an individual, object or system using a standardised evaluation procedure.',
    'training': 'Services that provide instruction or practice, designed to impart proficiency or improve efficiency. For other aspects of training, use another service type from the list where available (eg, ‘certificates’, ‘enquiries’, ‘enrolments’).',
    'transactions': 'Any online service and/or assistance that functions as an intermediary between the user and online data or information, for which a more specific service type is not listed.',
}

# https://data.naa.gov.au/def/agift/NATURAL-RESOURCES.html
agift = {
    'Crown land administration',
    'Energy resources',
    'Land use planning',
    'Land valuation',
    'Mineral resources',
    'Pollution emission control',
    'Water resources'
}
